Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScoreStore.Data;
using ScoreStore.Models;

namespace ScoreStore.Controllers
{
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GamesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            return View(await _context.Game.ToListAsync());
        }

        // GET: Games
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> IndexAdmin()
        {
            return View(await _context.Game.ToListAsync());
        }

        // GET: Games/Details/5
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ImageURL")] Game game)
        {
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        // GET: Games/Edit/5
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ImageURL")] Game game)
        {
            if (id != game.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        // GET: Games/Delete/5
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var game = await _context.Game.FindAsync(id);
            _context.Game.Remove(game);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameExists(int id)
        {
            return _context.Game.Any(e => e.Id == id);
        }
    }
}

Controllers/ScoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScoreStore.Data;
using ScoreStore.Models;

namespace ScoreStore.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class ScoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ScoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Scores
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Scores.Include(s => s.Game).Include(s => s.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Scores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scores = await _context.Scores
                .Include(s => s.Game)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scores == null)
            {
                return NotFound();
            }

            return View(scores);
        }

        // GET: Scores/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Game, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Scores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Wins,Losses,UserId,GameId")] Scores scores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(scores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Game, "Id", "Id", scores.GameId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", scores.UserId);
            return View(scores);
        }

        // GET: Scores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scores = await _context.Scores.FindAsync(id);
            if (scores == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Game, "Id", "Id", scores.GameId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", scores.UserId);
            return View(scores);
        }

        // POST: Scores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Wins,Losses,UserId,GameId")] Scores scores)
        {
            if (id != scores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(scores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScoresExists(scores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Game, "Id", "Id", scores.GameId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", scores.UserId);
            return View(scores);
        }

        // GET: Scores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scores = await _context.Scores
                .Include(s => s.Game)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scores == null)
            {
                return NotFound();
            }

            return View(scores);
        }

        // POST: Scores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var scores = await _context.Scores.FindAsync(id);
            _context.Scores.Remove(scores);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScoresExists(int id)
        {
            return _context.Scores.Any(e => e.Id == id);
        }
    }
}

Views/Home/AddScore.cshtml
@model IEnumerable<ScoreStore.Models.ApplicationUser>

<!--dismissable honor system alert -->
<div class="alert alert-info alert-dismissible alert-" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <i>ScoreStore</i> works best on the honor system! If you and your friends are truthful about the winners of your matches, the scores will make more sense when you view and compare each other's stats.
</div>

<div class="row">
    <div class="col-sm-12 text-center stats-header">
        <div class="row text-light jumbotron-main">
            <h3>Add a Score for '@ViewBag.Title'</h3>
        </div>
        <div class="row bg-dark">
            <div class="col-sm-2 text-light" style="width:100%;padding:24px;">
                Did you win or lose? If you lost, select the friend that was the better player or choose <i>Other</i> if the winner does not appear in your friend list. <strong>Scores cannot be undone once submitted.</strong>
            </div>
        </div>
    </div>
</div>
<div class="row chart-box-2 justify-content-center align-items-center text-dark" style="padding:24px;margin:48px;">
    <div class="col-sm-6 d-flex justify-content-center">
        <div id="div_winorloss" style="font-size: 24px;">
            <input onClick="CheckSelection()" class="form-check-input" type="radio" id="rb_win" name="result" value="win" style="margin-top:4px;" checked>
            <label class="form-check-label" for="rb_win" style="margin-left:12px;margin-bottom:24px;">
                <b>I won!</b><i class="fa-solid fa-face-smile icon-radio"></i>
            </label>
            <br>
            <input onClick="CheckSelection()" class="form-check-input" type="radio" id="rb_loss" name="result" value="loss">
            <label class="form-check-label" for="rb_loss" style="margin-left:12px;">
                <b>I lost...</b><i class="fa-solid fa-face-frown icon-radio"></i>
            </label>
            <br>
        </div>
    </div>
    <div class="col-sm-6 d-flex justify-content-center" style="border-left: 2px solid #1b1b1e;">
        <div id="div_selectfriend">
            @foreach (var item in Model)
            {
                <input class="form-check-input" type="radio" id="@item.Name" name="winner" value="@item.Name" disabled>
                <label class="form-check-label" for="@item.Name">
                    <img class="avatar" src="~/img/user-icons/@item.Avatar" alt="@item.Name's Avatar">
                    @item.Name
                </label><br>
            }
            <input class="form-check-input" type="radio" id="{x}" name="winner" value="{x}" disabled>
            <label class="form-check-label" for="{x}"><i>Other</i></label>
        </div>
    </div>
</div>
<div class="row text-center">
    <div class="col-sm-6">
        <p>
            <a class="btn btn-danger btn-md" role="button" asp-action="ViewGame" asp-route-id="@ViewBag.GameId">
                Cancel Score
            </a>
        </p>
    </div>
    <div class="col-sm-6">
        <div>
            <button class="btn btn-primary btn-md" onClick="ConfirmScore()">Submit Score</button>
        </div>
    </div>
</div>

<script type="text/javascript">

    // obtain Id of current game to update score for
    var gameId = @(ViewBag.GameId);

    /**
     * Enables or disables the radio buttons of the friend list depending on whether
     * or not the user has marked that they won or lost this game.
     * Marking a loss should enable the friend list to then prompt the user to select
     * the winner of the game. If this user won, the friend list should be disabled.
     */
    function CheckSelection() {

        // get reference to radio button specifying if user won
        var rb_win = document.getElementById("rb_win");

        // get reference to all radio button inputs in the populated friend list
        var rb_friends = document.getElementById("div_selectfriend").getElementsByTagName("input");

        // only enable friend list radio buttons if user did not mark that they won
        for (let i = 0; i < rb_friends.length; i++) {
            rb_friends[i].disabled = rb_win.checked;
        }
    }

    /**
     * Submits the score selection of who won this particular game and returns the
     * user to the ViewGame page for this game.
     * Will alert the user if no friend was selected as the winner if the user
     * marked themselves as the loser.
     * Uses Id routing value to specify who won:
     *  {0}: current user won
     *  {rb_friends[i].value}: user Id of friend that won
     *  {x}: user not currently in friend list that won
     */
    function ConfirmScore() {

        // user marked themselves as the winner
        if (document.getElementById("rb_win").checked) {

            // call asp action from controller to submit user as winner for this score
            window.location.href = '@Url.Action("SubmitScore", "Home")?game=' + gameId + '&name={0}';
        } else {

            // create flag for identifying if a winner was selected
            let winnerSelected = false;

            // get reference to all radio button inputs in the populated friend list
            var rb_friends = document.getElementById("div_selectfriend").getElementsByTagName("input");

            // search for friend that was marked as winner
            for (let i = 0; i < rb_friends.length; i++) {

                // if found, call asp action from controller to submit friend as winner for this score
                if (rb_friends[i].checked) {
                    window.location.href = '@Url.Action("SubmitScore", "Home")?game=' + gameId + '&name=' + rb_friends[i].value;
                    winnerSelected = true;
                }
            }

            // alerts the user that a winner needs to be selected from the friend list
            if (!winnerSelected)
                alert("You must select a user as a winner of this game.");
        }
    }
</script>

Views/Home/AdminMenu.cshtml
@{
    ViewData["Title"] = "Admin Tools";
}

<!--based on bootstrap jumbotron example -->
<div class="jumbotron text-dark jumbotron-main">
    <div class="container">
        <h1 class="display-3">Admin Tools</h1>
        <p>Administrative control panel with read/write access to all crucial data tables that <i>ScoreStore</i> requires for operation. Available only to the administrator account.</p>
    </div>
</div>

<div class="container">

    <div class="row">
        <div class="col-md-4 text-light bg-dark jumbotron-sub">
            <h2>Games</h2>
            <p>Access the table for the <code>/Models/Game</code> object. Read, update and delete commands available.</p>
            <p><a class="btn btn-secondary" role="button" asp-area="" asp-controller="Games" asp-action="IndexAdmin">View games &raquo;</a></p>
        </div>
        <div class="col-md-4 text-light jumbotron-sub">
            <h2>Scores</h2>
            <p>Access the table for the <code>/Models/Scores</code> object. Create, read, update and delete commands available.</p>
            <p><a class="btn btn-secondary" role="button" asp-area="" asp-controller="Scores" asp-action="Index">View scores &raquo;</a></p>
        </div>
        <div class="col-md-4 text-light bg-dark jumbotron-sub">
            <h2>Users</h2>
            <p>Access the table for the <code>/Models/ApplicationUser</code> object. Search and read commands available.</p>
            <p><a class="btn btn-secondary" role="button" asp-area="" asp-controller="Home" asp-action="UserIndexAdmin">View users &raquo;</a></p>
        </div>
    </div>

    <hr>

</div> <!-- /container -->

Views/Home/FriendList.cshtml
@model List<(string Id, string Name, string Avatar, string NormalizedEmail, double Ratio, int Matches, int Games)>

<div style="margin-top:18px;margin-left:18px;">
    <a class="btn btn-primary btn-sm games-header" role="button" asp-action="SearchUsersResults">
        Add Friend
        <i class="fa-solid fa-plus icon-add"></i>
    </a>
    <h4 class="games-header" style="margin-left:18px;">My Friends</h4>
</div>

<hr>

@foreach (var item in Model)
{
    <div class="row list-item bg-dark text-light" onClick="ViewFriendStats('@item.Id')">
        <div class="col-sm-2 d-flex justify-content-center list-item-img">
            <img class="list-item-img" src="~/img/user-icons/@item.Avatar" alt="@item.Name's Avatar">
        </div>
        <div class="col-sm-10">
            <div class="row list-item-title">
                <div class="col-sm-8">
                    <h3 style="margin-top:4px;">@Html.DisplayFor(modelItem => item.Name)</h3>
                </div>
                <div class="col-sm-4 text-right">
                    <i class="fa-solid fa-xmark fa-2x icon-remove" onClick="event.stopPropagation();ConfirmFriendRemoval('@item.Name', '@item.Id')"></i>
                </div>
            </div>
            <div class="row text-center" style="margin-top:16px;">
                <div class="col-sm-2 list-item-detail">
                    @Html.DisplayFor(modelItem => item.Ratio)% winrate
                </div>
                <div class="col-sm-1">|</div>
                @if (item.Matches == 1)
                {
                    <div class="col-sm-2 list-item-detail">
                        @Html.DisplayFor(modelItem => item.Matches) match
                    </div>
                }
                else
                {
                    <div class="col-sm-2 list-item-detail">
                        @Html.DisplayFor(modelItem => item.Matches) matches
                    </div>
                }
                <div class="col-sm-1">|</div>
                @if (item.Games == 1)
                {
                    <div class="col-sm-2 list-item-detail">
                        plays @Html.DisplayFor(modelItem => item.Games) game
                    </div>
                }
                else
                {
                    <div class="col-sm-2 list-item-detail">
                        plays @Html.DisplayFor(modelItem => item.Games) games
                    </div>
                }
                <div class="col-sm-1 text-right">
                    <i class="fa-solid fa-angles-right fa-2x icon-view"></i>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    /**
     * Redirects the user to the overall stats page for this friend.
     */
    function ViewFriendStats(id) {

        // call asp action from controller to view specified friend (and clear ambient routing value)
        window.location.href = '@Url.Action("ViewFriend", "Home", new { id = "" })/' + id;
    }

    /**
     * Prompts a dialog to the user for confirming removal of the specified friend
     * from their friend list.
     */
    function ConfirmFriendRemoval(friend, id) {

        // dialog message to display
        let msg = "Are you sure you want to remove '" + friend + "' from your friend list?";

        // prompt dialog to confirm removal of specified friend
        if (confirm(msg) == true) {

            // call asp action from controller to remove specified friend (and clear ambient routing value)
            window.location.href = '@Url.Action("RemoveFriend", "Home", new { id = "" })/' + id;
        }
    }
</script>

Views/Home/GameList.cshtml
@model List<(int Id, string ImageURL, string Title, double Ratio, int Matches)>

<div style="margin-top:18px;margin-left:18px;">
    <a class="btn btn-primary btn-sm games-header" role="button" asp-controller="Games" asp-action="Index">
        Add Game
        <i class="fa-solid fa-plus icon-add"></i>
    </a>
    <h4 class="games-header" style="margin-left:18px;">My Games</h4>
</div>

<hr>

@foreach (var item in Model)
{
    <div class="row list-item bg-dark text-light" onClick="ViewGameStats('@item.Id')">
        <div class="col-sm-2 d-flex justify-content-center list-item-img">
            <img class="list-item-img" src="@item.ImageURL" alt="@item.Title Cover Art ">
        </div>
        <div class="col-sm-10">
            <div class="row list-item-title">
                <div class="col-sm-8">
                    <h3 style="margin-top:4px;">@Html.DisplayFor(modelItem => item.Title)</h3>
                </div>
                <div class="col-sm-4 text-right">
                    <i class="fa-solid fa-xmark fa-2x icon-remove" onClick="event.stopPropagation();ConfirmGameRemoval('@item.Title', '@item.Id')"></i>
                </div>
            </div>
            <div class="row text-center" style="margin-top:16px;">
                <div class="col-sm-3 list-item-detail">
                    @Html.DisplayFor(modelItem => item.Ratio)% winrate
                </div>
                <div class="col-sm-2">|</div>
                @if (item.Matches == 1)
                {
                    <div class="col-sm-3 list-item-detail">
                        @Html.DisplayFor(modelItem => item.Matches) match
                    </div>
                }
                else
                {
                    <div class="col-sm-3 list-item-detail">
                        @Html.DisplayFor(modelItem => item.Matches) matches
                    </div>
                }
                <div class="col-sm-1 text-right">
                    <i class="fa-solid fa-angles-right fa-2x icon-view"></i>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    /**
     * Redirects the user to the stats page for this game.
     */
    function ViewGameStats(id) {

        // call asp action from controller to view specified game (and clear ambient routing value)
        window.location.href = '@Url.Action("ViewGame", "Home", new { id = "" })/' + id;
    }

    /**
     * Prompts a dialog to the user for confirming removal of the specified game
     * from their game list.
     */
    function ConfirmGameRemoval(title, id) {

        // dialog message to display
        let msg = "Are you sure you want to remove '" + title + "' from your game list?";
        let note = "Scores for this game will not be deleted should you choose to add it back later.";

        // prompt dialog to confirm removal of specified game
        if (confirm(msg + "\n\n" + note) == true) {

            // call asp action from controller to remove specified game (and clear ambient routing value)
            window.location.href = '@Url.Action("RemoveGame", "Home", new { id = "" })/' + id;
        }
    }
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!--dismissable free service warning -->
<div class="alert alert-warning alert-dismissible alert-" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <i>ScoreStore</i> is hosted on free web and database services. Please do not abuse the limits of these free services by:
    <ul>
        <li>limiting yourself to one account</li>
        <li>ending your session as quickly as possible to avoid utlizing the maximum concurrent connections</li>
        <li>tracking the scores of just a handful of games to save on the database quota</li>
    </ul>
	⚠️ <b>Should <i>ScoreStore</i> be unavailable, it is likely the <u>monthly resource limit</u> was reached. Please check back next month when it resets.</b> ⚠️
</div>

<!--based on bootstrap jumbotron example -->
<div class="jumbotron text-dark jumbotron-main">
    <div class="container">
        <h1 class="display-3">ScoreStore</h1>
        <p>Keep track of all the different games you like to play and how often you win. Let <i>ScoreStore</i> do the rest by providing you with the tools to best make sense of how you and your friends stack up.</p>
        @if (!User.Identity.IsAuthenticated)
        {
            <p><a class="btn btn-primary btn-lg" role="button" asp-area="Identity" asp-page="/Account/Register">Get started &raquo;</a></p>
        }
    </div>
</div>

<div class="container">

    <div class="row">
        <div class="col-md-4 text-light bg-dark jumbotron-sub">
            <h2>Submit Scores</h2>
            <p>For any game you decide to add to your profile, you'll be able to update your scores by simply marking a win or a loss. There's no limit to how many games you can add or to the scores you need to keep.</p>
            <p><a class="btn btn-secondary" role="button" asp-area="" asp-controller="Games" asp-action="Index">Add games &raquo;</a></p>
        </div>
        <div class="col-md-4 text-light jumbotron-sub">
            <h2>Track Trends</h2>
            <p>View a variety of statistics for each individual game you have on your profile. Through visual charts dynamically prepared for you, you'll be able to better understand your scores across time. Ever wanted to know your win ratio?</p>
            <p><a class="btn btn-secondary" role="button" asp-area="" asp-controller="Home" asp-action="GameList">View stats &raquo;</a></p>
        </div>
        <div class="col-md-4 text-light bg-dark jumbotron-sub">
            <h2>Compare Competition</h2>
            <p>Invite friends to create their own profiles and track their own scores. Then, simply add your buddies to your own friend list to see how they perform in their favorite games. Make rivals and uncover who the real champion is!</p>
            <p><a class="btn btn-secondary" role="button" asp-area="" asp-controller="Home" asp-action="SearchUsersResults">Find friends &raquo;</a></p>
        </div>
    </div>

    <hr>

</div> <!-- /container -->

Views/Home/MissingUser.cshtml
@{
    ViewData["Title"] = "User Not Found";
}

<div>
    <a asp-action="FriendList">Back to List</a>
</div>
<hr />

<h1>@ViewData["Title"]</h1>

<p>An error occurred while loading this user. The account has most likely been deleted.</p>

Views/Home/ReportIssue.cshtml
@{
    ViewData["Title"] = "Report an Issue";
}
<div class="text-center">
    <h1 class="display-4">Reporting an Issue</h1>
    <p>If you believe you've identified a <b>technical</b> issue, please <a href="https://github.com/kkevn/ScoreStore/issues/new?assignees=kkevn&labels=bug%2Cissue+report&template=issue_report.yml&title=%5BIssue%5D%3A+">submit a report</a> on the official GitHub issue tracker and provide the following information when asked for details regarding the issue:</p>

    <hr>

    <div style="text-align: center;">
        <pre class="text-light" style="display: inline-block; text-align: left;">

        <code>/* Generalize the issue in the title. */</code>

        <b>Summary</b>:
        Give a brief description of the issue.

        <b>Steps to Reproduce</b>:
        Number any necessary steps that led to this issue.

        <b>Actual Result</b>:
        State what occurs when the reproduction steps are followed.

        <b>Expected Result</b>:
        State what outcome was expected when the reproduction steps are followed.
        </pre>
    </div>

    <hr>

    <p><i>Failure to submit an issue report in this format will likely lead to the report being ignored due to insufficient information.</i></p>
</div>

Views/Home/UserEdit.cshtml
@model ScoreStore.Models.ApplicationUser

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ApplicationUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UserEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UserName" />
            <input type="hidden" asp-for="NormalizedUserName" />
            <input type="hidden" asp-for="Email" />
            <input type="hidden" asp-for="NormalizedEmail" />
            <input type="hidden" asp-for="EmailConfirmed" />
            <input type="hidden" asp-for="PasswordHash" />
            <input type="hidden" asp-for="SecurityStamp" />
            <input type="hidden" asp-for="ConcurrencyStamp" />
            <input type="hidden" asp-for="PhoneNumber" />
            <input type="hidden" asp-for="PhoneNumberConfirmed" />
            <input type="hidden" asp-for="TwoFactorEnabled" />
            <input type="hidden" asp-for="LockoutEnd" />
            <input type="hidden" asp-for="LockoutEnabled" />
            <input type="hidden" asp-for="AccessFailedCount" />
            <input type="hidden" asp-for="FriendList" />
            <input type="hidden" asp-for="GameList" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avatar" class="control-label"></label>
                <input asp-for="Avatar" class="form-control" />
                <span asp-validation-for="Avatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreakList" class="control-label"></label>
                <input asp-for="StreakList" class="form-control" />
                <span asp-validation-for="StreakList" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="UserIndexAdmin">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}